version: ~> 1.0
dist: bionic
language: python
cache: pip
jobs:
  include:
    - env: TOXENV=py37
      python: 3.7
install:
  - ./.githooks/deploy.sh
  - nvm install
  - npm ci
  - pip install tox coveralls
script:
  - make test-ci
after_success:
  - coveralls
notifications:
  email: false
