version: ~> 1.0
dist: bionic
language: python
cache: pip
jobs:
  include:
    - env: TOXENV=py37-dj22
      python: 3.7
    - env: TOXENV=py37-dj30
      python: 3.7
install:
  - ./.githooks/deploy.sh
  - nvm install
  - npm ci
  - pip install tox==3.14.5 coveralls==1.11.1
script:
  - make test-ci
after_success:
  - coveralls
notifications:
  email: false
